/**
 * Print-ready report renderer. Returns the body fragment (header + summary
 * + filters + projects + footer) to be inserted into the dedicated report
 * extension page (`src/report/report.html`). A dedicated page is needed
 * because a `blob:` URL inherits a CSP that blocks all scripts, so the
 * print button cannot be wired up there.
 */

import type { TimeEntry, DateRange } from '../lib/attendance.js';
import { escapeHtml, fmtHours } from '../lib/format.js';
import { UNKNOWN } from '../lib/constants.js';

type Filters = { employee: string; project: string; search: string };

export interface ReportPayload {
  range: DateRange;
  filters: Filters;
  entries: TimeEntry[];
}

export interface RenderedReport {
  /** Used as document.title of the report page. */
  title: string;
  /** HTML fragment to inject into `#root`. */
  bodyHtml: string;
}

export function renderReport(opts: ReportPayload): RenderedReport {
  const { range, filters, entries } = opts;
  const total = entries.reduce((s, e) => s + e.hours, 0);

  const projectMap = new Map<string, Map<string, TimeEntry[]>>();
  for (const e of entries) {
    const proj = e.project || UNKNOWN;
    const emp = e.employee || UNKNOWN;
    if (!projectMap.has(proj)) projectMap.set(proj, new Map());
    const empMap = projectMap.get(proj)!;
    if (!empMap.has(emp)) empMap.set(emp, []);
    empMap.get(emp)!.push(e);
  }
  const projects = Array.from(projectMap.entries())
    .map(([proj, empMap]) => {
      const employees = Array.from(empMap.entries())
        .map(([emp, items]) => ({
          name: emp,
          hours: items.reduce((s, e) => s + e.hours, 0),
          entries: items.slice().sort((a, b) => a.date.localeCompare(b.date)),
        }))
        .sort((a, b) => b.hours - a.hours);
      const projTotal = employees.reduce((s, e) => s + e.hours, 0);
      return { project: proj, hours: projTotal, employees };
    })
    .sort((a, b) => b.hours - a.hours);

  const generated = new Date().toLocaleString();
  const titleRange = `${range.from} → ${range.to}`;

  const projectsHtml = projects.map((p) => {
    const employeesHtml = p.employees.map((emp) => {
      const rowsHtml = emp.entries.map((e) => `
        <tr>
          <td>${escapeHtml(e.date)}</td>
          <td class="num">${fmtHours(e.hours)}</td>
          <td>${escapeHtml(e.activity)}</td>
          <td>${escapeHtml(e.comment)}</td>
        </tr>`).join('');
      return `
        <div class="emp-block">
          <h3>${escapeHtml(emp.name)} <span class="muted">— ${fmtHours(emp.hours)}</span></h3>
          <table>
            <thead><tr><th>Date</th><th class="num">Hours</th><th>Activity</th><th>Comment</th></tr></thead>
            <tbody>${rowsHtml}</tbody>
          </table>
        </div>`;
    }).join('');
    const pct = total > 0 ? ((p.hours / total) * 100).toFixed(1) : '0.0';
    return `
      <section class="project">
        <h2>${escapeHtml(p.project)} <span class="muted">— ${fmtHours(p.hours)} (${pct}%)</span></h2>
        ${employeesHtml}
      </section>`;
  }).join('');

  const bodyHtml = `
    <header>
      <h1>Time Report</h1>
      <div class="meta">${escapeHtml(titleRange)} · generated ${escapeHtml(generated)}</div>
    </header>
    <div class="summary">
      <div class="kpi"><span>Total hours</span><strong>${fmtHours(total)}</strong></div>
      <div class="kpi"><span>Entries</span><strong>${entries.length}</strong></div>
      <div class="kpi"><span>Projects</span><strong>${projects.length}</strong></div>
    </div>
    <div class="filters">
      Filters: <b>Employee:</b> ${escapeHtml(filters.employee)} · <b>Project:</b> ${escapeHtml(filters.project)}${filters.search ? ` · <b>Search:</b> ${escapeHtml(filters.search)}` : ''}
    </div>
    ${projectsHtml || '<p style="color:#888">No entries match the current filters.</p>'}
    <footer>Generated by Time Sheet Reporting Toolkit · unofficial · not affiliated with Personio SE · ${escapeHtml(generated)}</footer>
  `;

  return { title: `Time Report ${titleRange}`, bodyHtml };
}
